# Team MakePittsburghAmericaAgain (MPAA)
### Aaron Palmer, Pran Sutham

### Introduction:

What makes a neighborhood the best one in its city? Though there are infinitely many approaches to answering this question, we have decided to give it a try ourselves and came up with this project to determine the **best neighborhood in Pittsburgh.**

The goal of this project is to not only arrive at an answer but a **data-driven** one using official datasets provided by the Western Pennsylvania Regional Data Center (WPRDC).

After spending considerable time thinking, we agreed on defining the best neighborhood in Pittsburgh as the one that’s **the most** supremely and quintessentially **A M E R I C A N**. In other words, the more "American" a neighborhood is, the better. Keeping this in mind, we came up with criteria examining traits that we believe affect a neighborhood’s “Americanness”. Those said criteria form the metrics explained in detail later in this report.

Some alternative topics/metrics we considered throughout this process were the most health-insured, the most educated and the most gun. However, these were ultimately scrapped in large due to us being unable to find datasets that we thought gave us enough information about these things.

### The Metric:

Our main metric, the **MPAA score** (short for MakePittsburghAmericaAgain), is divided into three smaller sub-metrics. As stated previously, this metric is intended to assess how American a neighborhood which - in our opinion - determines how "good" it is. The MPAA score (with limited information) measures how well-armed, well-fed and technologically advanced a Pittsburgh neighborhood is. These three sub-metrics are explained in greater detail below.

**Sub-Metric 1**: The most well-armed

The United States of America is world-famous for its gun culture, and many Americans are overtly proud of exercising their Second Amendment rights. It is hard to deny that firearms are a big part of the American identity. 

For this first sub-metric, we used the "Firearms Seizures Data" dataset from the Police Bureau / Department of Public Safety (link: https://data.wprdc.org/dataset/pbp-fire-arm-seizures). "The most armed" neighborhood is defined as the neighborhood with the lowest number of total firearm seizures (labeled as "total_count" in the dataset). The reasoning behind choosing this dataset is that the higher the number of firearm seizures is for a neighborhood, the greater the likelihood that it is well-armed.

**Sub-Metric 2:** The most well-fed

The United States of America is also world-famous for its abundance of food and resultantly, its alarming rate of obesity. Americans lead the developed world in percentage of obese people and remain near the top of the charts for the entire world. 

For this second sub-metric, we used the "Obesity Rates Allegheny County Data" dataset from the Department of Health (link: https://data.wprdc.org/dataset/allegheny-county-obesity-rates). "The most well-fed" neighborhood is defined as the neighborhood with the highest estimated rate of obesity (labeled as "2006-2010 estimate of obesity" in the dataset). The estimated rate of obesity is a number ranging from 0 to 1 with 1 being the highest possible rate of obesity for a neighborhood; a neighborhood with an estimated rate of obesity of 1 would mean that all its citizens are obese. The reasoning behind choosing this dataset is simple: as a neighborhood becomes more well-fed, its rate of obesity should likely (but not always) go up. 

We must note, however, that there are some limitations and factors to keep in mind for this sub-metric. First, the numbers used here are outdated and thus may not reflect the current obesity situation in Pittsburgh. Additionally, no clear definition of "obesity" is provided meaning that there is a chance that overweight people (and not necessarily *only* obese people) are counted as well.

**Sub-Metric 3:** The most technologically advanced

In spite of the "dumb, culturally ignorant American" stereotype, the United States remains a technological powerhouse and a breeding ground of research and innovation. In fact, an overwhelming number of technological breakthroughs in the past two centuries can be traced back to the Land of Opportunity.

For this third sub-metric, we used the "Smart Trash Containers" dataset from the Department of Public Works (link: https://data.wprdc.org/dataset/smart-trash-containers). "The most technologically advanced" neighborhood is defined as the neighborhood with the highest number of smart trash containers with each row in the dataset representing a single smart trash container. The reasoning behind choosing this dataset is that smart trash containers are fancy technological gadgets that a technologically unadvanced neighborhood would likely have very little of, if any.

### Metric 1: The most armed

In [9]:
import pandas as pd
import numpy as np

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

In [10]:
pgh_armed_data = pd.read_csv("https://data.wprdc.org/datastore/dump/e967381d-d7e9-48e3-a2a2-39262f7fa5c4")
pgh_armed_data.head()

,address,total_count,other_count,pistol_count,revolver_count,rifle_count,shotgun_count,year,month,dow,neighborhood,council_district,ward,tract,public_works_division,police_zone,fire_zone,latitude,longitude
0,"1700 BLOCK ARLINGTON AVE PITTSBURGH, PA 15210",2,0,1,1,0,0,2015,1,0,Mount Oliver Borough,3.0,0.0,4.200317e+10,0.0,3,4-6,40.417619,-79.986436
1,"BREVET WAY & MINTON ST PITTSBURGH, PA 15204",1,0,1,0,0,0,2015,1,0,Sheraden,2.0,20.0,4.200356e+10,5.0,6,1-16,40.456904,-80.052328
2,"TERRACE ST & WHITRIDGE ST PITTSBURGH, PA 15213",1,0,1,0,0,0,2015,1,0,Terrace Village,6.0,4.0,4.200305e+10,3.0,2,2-10,40.441185,-79.968527
3,"3500 BLOCK GERBER AVE PITTSBURGH, PA 15212",1,0,1,0,0,0,2015,1,0,Brighton Heights,1.0,27.0,4.200327e+10,1.0,1,1-14,40.479530,-80.033477
4,"7500 BLOCK KELLY ST PITTSBURGH, PA 15208",1,0,1,0,0,0,2015,1,0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN

In [7]:
pgh_armed_data.pivot(columns = "neighborhood", values = "total_count").head()

neighborhood,NaN,Allegheny Center,Allegheny West,Allentown,Arlington,Arlington Heights,Banksville,Bedford Dwellings,Beechview,Beltzhoover,...,Strip District,Summer Hill,Terrace Village,Troy Hill,Upper Hill,Upper Lawrenceville,West End,West Oakland,Westwood,Windgap
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pgh_armed_data.groupby("neighborhood").head()

,address,total_count,other_count,pistol_count,revolver_count,rifle_count,shotgun_count,year,month,dow,neighborhood,council_district,ward,tract,public_works_division,police_zone,fire_zone,latitude,longitude
0,"1700 BLOCK ARLINGTON AVE PITTSBURGH, PA 15210",2,0,1,1,0,0,2015,1,0,Mount Oliver Borough,3.0,0.0,4.200317e+10,0.0,3,4-6,40.417619,-79.986436
1,"BREVET WAY & MINTON ST PITTSBURGH, PA 15204",1,0,1,0,0,0,2015,1,0,Sheraden,2.0,20.0,4.200356e+10,5.0,6,1-16,40.456904,-80.052328
2,"TERRACE ST & WHITRIDGE ST PITTSBURGH, PA 15213",1,0,1,0,0,0,2015,1,0,Terrace Village,6.0,4.0,4.200305e+10,3.0,2,2-10,40.441185,-79.968527
3,"3500 BLOCK GERBER AVE PITTSBURGH, PA 15212",1,0,1,0,0,0,2015,1,0,Brighton Heights,1.0,27.0,4.200327e+10,1.0,1,1-14,40.479530,-80.033477
4,"7500 BLOCK KELLY ST PITTSBURGH, PA 15208",1,0,1,0,0,0,2015,1,0,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2853,"900 BLOCK N BRADDOCK AVE PITTSBURGH, PA 15221",1,0,1,0,0,0,2019,11,5,Regent Square,5.0,14.0,4.200314e+10,3.0,4,2-16,40.435655,-79.896187
2859,"1600 BLOCK DUFFIELD ST PITTSBURGH, PA 15206",1,0,1,0,0,0,2019,11,5,Morningside,7.0,10.0,4.200310e+10,2.0,5,3-7,40.482887,-79.930454
2907,"1900 BLOCK JANCEY ST PITTSBURGH, PA 15206",1,0,1,0,0,0,2019,12,6,Morningside,7.0,10.0,4.200310e+10,2.0,5,3-7,40.487747,-79.924709
2959,"1600 BLOCK DUFFIELD ST PITTSBURGH, PA 15206",1,0,0,0,1,0,2020,2,2,Morningside,7.0,10.0,4.200310e+10,2.0,5,3-7,40.482887,-79.930454
2961,"800 BLOCK BALDWIN RD PITTSBURGH, PA 15207",2,0,2,0,0,0,2020,2,2,Hays,5.0,31.0,4.200356e+10,3.0,4,4-20,40.377716,-79.937664

### Metric 2: The most well-fed

In [21]:
pgh_obese_data = pd.read_csv("https://data.wprdc.org/dataset/b049da40-910a-4b9d-9438-ff584e432bb1/resource/fce248f0-8697-4d2a-bbe0-2da826776bfa/download/obesity-ac-2006-2010censustracts.csv")
pgh_obese_data.head()

,stname,tractfips,2000 Tract,2010 Tract,MUNICIPALITY,Municipality,City Neighborhood,2006-2010 estimate of obesity
0,Pennsylvania,42003010300,10300,NaN,PITTSBURGH,Pittsburgh,Bluff,0.246936
1,Pennsylvania,42003020100,20100,NaN,PITTSBURGH,Pittsburgh,Central Business District,0.668012
2,Pennsylvania,42003020300,20300,NaN,PITTSBURGH,Pittsburgh,Strip District,0.369996
3,Pennsylvania,42003030500,30500,NaN,PITTSBURGH,Pittsburgh,Crawford Roberts,0.488691
4,Pennsylvania,42003040200,40200,NaN,PITTSBURGH,Pittsburgh,West oakland,0.366391

In [33]:
pgh_obese_data.pivot(columns = "City Neighborhood", values = "2006-2010 estimate of obesity").head()

City Neighborhood,NaN,Allegheny Center,Allegheny West,Allentown,Arlington,Arlington Heights,Banksville,Bedford Dwellings,Beechview,Beltzhoover,...,Summer Hill,Swisshelm Park,Terrace Village,Troy Hill/Herr's Island,Upper Hill,Upper Lawrenceville,West End,West oakland,Westwood,Windgap
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.366391,NaN,NaN

### Metric 3: The most technologically advanced

Insert code and text here

### The BEST Neighborhood

Insert text here: 

- combine these 3 sub-metrics into one metric. determine the best neighborhood right now + over time (across the years and all that)

From the rubric:
- Apply the metric from the previous section to determine the best neighborhood in Pittsburgh. 
- Beyond just executing code, provide narrative about why you think this is the best neighborhood. 
- Incorporate a data visualization, perhaps to rank all of the neighborhoods or show a neighborhood’s best-ness over time.
- The KEY is to make a data driven argument.

### Conclusion:

**Aaron:**

XXXXXXXX


**Pran:**

Because I have never lived anywhere else and spent very little time exploring Pittsburgh this past year, Oakland is my personal favorite neighborhood in the city by default. XXX